name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 64000
        script: |
          PROJECT_DIR="/var/www/html/cicd/mala-dimas-linka"
          
          # Make sure directories exist
          mkdir -p $PROJECT_DIR
          
          cd $PROJECT_DIR

          # Clone or pull latest changes
          if [ ! -d ".git" ]; then
            git clone https://github.com/${{ github.repository }}.git .
          else
            git pull origin master
          fi

          # Set correct permissions for project only
          chmod -R 755 $PROJECT_DIR
